/**
 * Created by THIPHUNG on 11/16/2016.
 */
export const appName="around";


export const platform="web";
export const VERSON_APP = '1.0.6';
export const otpKey= "WQ34Y33CCL53H25F";
export const encryptKey="RjVYQ1NSSEJGQTUySFpaNA==";
export const googleMapURL = "https://maps.googleapis.com/maps/api/js?key="+GOOGLE_API_KEY+"&amp;v=3.exp&amp;signed_in=true";
export const locationCheckPoint = 'locationCheckPoint';
export const SESSION_NAME_CHECKOUT_NL_TOKEN = 'checkoutNganluongToken';
export const SESSION_NUMBER_ACOIN_BUY = 'numberACoinBuy';

export const linkApi="http://127.0.0.1:1337";               //development
// export const linkApi="http://test.api.around.com.vn";    //test
// export const linkApi="https://api.around.com.vn";        //production

// export const linkServerImage="http://localhost:8080/static/img/";          //development
export const linkServerImage = "https://around.com.vn/static/img/";     //production

export const linkImagesStatic = "https://api.around.com.vn";
export const linkDieuKhoan="https://around.com.vn/dieukhoan.html";
export const linkHelp = "https://around.com.vn/huong-dan/index.html";
export const linkAppIOS = "https://itunes.apple.com/us/app/around-m%E1%BA%A1ng-x%C3%A3-h%E1%BB%99i-%C4%91%E1%BB%8Ba-%C4%91i%E1%BB%83m/id1280830100?ls=1&mt=8";
export const linkAppAndroind = "https://play.google.com/store/apps/details?id=around.littleworld&hl=vi";
export const SESSION_DEFAULT_LOGIN = 'e10adc3949ba59abbe56e057f20f883e';
export const SESSION_NAME_REQUEST = 'sessionAround';
export const DATA_REQUEST_SEARCH_CRV = 'dataRequestSearchCRV';
export const TIME_RELOAD = 60000;
export const DEFAULT_PARENT = -1;
export const STATE_ADS_PAUSE = 0;
export const STATE_ADS_PLAY = 1;
export const STATE_ADS_PENDING = 2;
export const STATUS_ACTIVE = 1;
export const STATUS_PENDING = 0;
export const STATUS_DELETE = -2;
export const STATE_ACTIVE = 1;
export const STATE_PENDING = 0;
export const STATE_DELETE = -2;
export const TYPE_JOBS = 2;
export const TYPE_CATEGORY = 1;
export const STATUS_SHOP_INFO = 1;
export const KIND_BUY_PRODUCT_PT = 5;
export const KIND_LIKE = 1;
export const KIND_COMMENT = 2;
export const HIDDEN_PHONE = 0;
export const SHOW_PHONE = 1;
export const VIEW_ADS_VIDEO = 0;
export const VIEWED_ADS_VIDEO = 1;
/* webpack build*/
/*nginx build*/
// export const linkServerImage="http://"+window.location.host+"/portal/static/images/";
export const MAX_BUTTON_PAGGING=5;

export const KIND_BANNER_LON = 2;
export const KIND_BANNER_NHO = 3;
export const KIND_LIST_ACOIN = 2;

export const RESPONSE_CODE_SUCCESS= 1;
export const RESPONSE_CODE_ERROR=2;
export const RESPONSE_CODE_SESSION_INVALID=3;
export const RESPONSE_CODE_PARAM_INVALID=4;
export const RESPONSE_CODE_OTP_INVALID=5;
export const RESPONSE_CODE_APP_INVALID=6;
export const RESPONSE_CODE_DB_ERROR=7;
export const RESPONSE_CODE_NOT_ALLOW=8;
/*USER RESPONSE CODE*/
export const RESPONSE_CODE_ADD_USER_ERROR=100;
export const RESPONSE_CODE_UPDATE_USER_ERROR=101;
export const RESPONSE_CODE_LIST_USER_ERROR=102;
export const RESPONSE_CODE_DELETE_USER_ERROR=103;
export const RESPONSE_CODE_USER_EXIST=104;
export const RESPONSE_CODE_USER_NOT_FOUND=105;
export const RESPONSE_CODE_GET_USER_ERROR=106;
export const RESPONSE_CODE_USER_ADD_REFFERENCE_NOT_FOUND=107;
export const RESPONSE_CODE_LOGIN_USER_ERROR=108;
export const RESPONSE_CODE_LOGOUT_USER_ERROR=109;
export const RESPONSE_CODE_VERIFY_SESSION_ERROR=110;
export const RESPONSE_CODE_FORGOT_PASSWORD_ERROR=111;
export const RESPONSE_CODE_CHANGE_PASSWORD_ERROR=112;
export const RESPONSE_CODE_USER_BALANCE_NOT_ENOUGH = 115;
export const GOOGLE_API_KEY='AIzaSyDs7Y3GREuU3VqXSs6m2tuvWQwP0hn0jSI';//'AIzaSyBqmUIHtmcOTPAlWIb6qKV36ICKnKQ4gGc';
//export const API_KEY_AROUND='AIzaSyADZlqkIf23eKbGVaHxQHNXn6_0DxJpyb8';

export const GOOGLE_APP_ID = '592935117978-4n171hsobg28un2benr9nnrlt4vuo7ah.apps.googleusercontent.com'; //development

// export const FACEBOOK_APP_ID = '595121690592812';                        //production
// export const FACEBOOK_APP_SECRET = 'f18ea860d4b9ae0579796401e0c3bd59';   //production
export const FACEBOOK_APP_ID = '758973870941487';                        //test.around.com.vn
// export const FACEBOOK_APP_SECRET = '7f8e344e9d4ae36694e7bac9ca1faece';   //test.around.com.vn
// export const FACEBOOK_APP_ID = '1894488234171502';                          //development


/*RESPONSE_CODE_SUCCESS= 1,
 RESPONSE_CODE_ERROR= 2,
 RESPONSE_CODE_SESSION_INVALID= 3,
 RESPONSE_CODE_PARAM_INVALID= 4,
 RESPONSE_CODE_OTP_INVALID= 5,
 RESPONSE_CODE_APP_INVALID= 6,
 RESPONSE_CODE_NOT_ALLOW= 8,
 /!*USER RESPONSE CODE*!/
 RESPONSE_CODE_ADD_USER_ERROR=100,
 RESPONSE_CODE_UPDATE_USER_ERROR=101,
 RESPONSE_CODE_LIST_USER_ERROR=102,
 RESPONSE_CODE_DELETE_USER_ERROR=103,
 RESPONSE_CODE_USER_EXIST=104,
 RESPONSE_CODE_USER_NOT_FOUND=105,
 RESPONSE_CODE_GET_USER_ERROR=106,
 RESPONSE_CODE_USER_ADD_REFFERENCE_NOT_FOUND=107,
 RESPONSE_CODE_LOGIN_USER_ERROR=108,
 RESPONSE_CODE_LOGOUT_USER_ERROR=109,
 RESPONSE_CODE_VERIFY_SESSION_ERROR=110,
 RESPONSE_CODE_FORGOT_PASSWORD_ERROR=111,
 RESPONSE_CODE_CHANGE_PASSWORD_ERROR=112,
 RESPONSE_CODE_NEWS_FEED_ERROR=113,
 RESPONSE_CODE_USER_GET_BALANCE_ERROR=114,
 RESPONSE_CODE_USER_BALANCE_NOT_ENOUGH=115,
 RESPONSE_CODE_FRIEND_FEED_ERROR=116,

 /!*USER FRIEND RESPONSE CODE*!/
 RESPONSE_CODE_ADD_FRIEND_ERROR=200,
 RESPONSE_CODE_ACCEPT_ERROR=201,
 RESPONSE_CODE_LIST_FRIEND_ERROR=202,
 RESPONSE_CODE_BLOCK_FRIEND_ERROR=203,
 RESPONSE_CODE_UNBLOCK_FRIEND_ERROR=206,
 RESPONSE_CODE_FRIEND_EXIST=204,
 RESPONSE_CODE_USER_FRIEND_NOT_FOUND=205,
 RESPONSE_CODE_FRIEND_FIND_ERROR=207,
 RESPONSE_CODE_REF_NOT_FOUND=208,
 RESPONSE_CODE_DELETE_FRIEND_ERROR=209,
 RESPONSE_CODE_TRACKING_FRIEND_ERROR=210,

 /!*NATION RESPONSE CODE*!/
 RESPONSE_CODE_NATION_ADD_ERROR=300,
 RESPONSE_CODE_NATION_UPDATE_ERROR=301,
 RESPONSE_CODE_NATION_LIST_ERROR=302,
 RESPONSE_CODE_NATION_GET=303,
 RESPONSE_CODE_NATION_EXIST=304,

 /!*MESSAGE RESPONSE CODE*!/
 RESPONSE_CODE_MESSAGE_SEND_ERROR=400,
 RESPONSE_CODE_MESSAGE_LIST_ERROR=401,
 RESPONSE_CODE_MESSAGE_LIST_BY_THREAD_ERROR=402,
 RESPONSE_CODE_MESSAGE_DELETE_ERROR=403,

 /!*TYPES RESPONSE CODE*!/
 RESPONSE_CODE_TYPES_ADD_ERROR=500,
 RESPONSE_CODE_TYPES_UPDATE_ERROR=501,
 RESPONSE_CODE_TYPES_LIST_ERROR=502,
 RESPONSE_CODE_TYPES_GET_ERROR=503,
 RESPONSE_CODE_TYPES_EXIST=504,

 /!*SHOP RESPONSE CODE*!/
 RESPONSE_CODE_SHOP_ADD_ERROR=600,
 RESPONSE_CODE_SHOP_UPDATE_ERROR=601,
 RESPONSE_CODE_SHOP_LIST_ERROR=602,
 RESPONSE_CODE_SHOP_GET_ERROR=603,
 RESPONSE_CODE_SHOP_EXIST=604,
 RESPONSE_CODE_SHOP_NOT_FOUND=605,

 /!*POST RESPONSE CODE*!/
 RESPONSE_CODE_POST_ADD_ERROR=700,
 RESPONSE_CODE_POST_UPDATE_ERROR=701,
 RESPONSE_CODE_POST_LIST_ERROR=702,
 RESPONSE_CODE_POST_GET_ERROR=703,
 RESPONSE_CODE_POST_EXIST=704,
 RESPONSE_CODE_POST_NOT_FOUND=705,
 RESPONSE_CODE_POST_SOCIAL_ADD_ERROR=706,
 RESPONSE_CODE_POST_SOCIAL_EXIST=707,
 RESPONSE_CODE_POST_SOCIAL_LIST_ERROR=706,

 /!*Product RESPONSE CODE*!/
 RESPONSE_CODE_PRODUCT_ADD_ERROR=800,
 RESPONSE_CODE_PRODUCT_UPDATE_ERROR=801,
 RESPONSE_CODE_PRODUCT_LIST_ERROR=802,
 RESPONSE_CODE_PRODUCT_GET_ERROR=803,
 RESPONSE_CODE_PRODUCT_EXIST=804,
 RESPONSE_CODE_PRODUCT_NOT_FOUND=805,
 RESPONSE_CODE_BUY_PRODUCT_ERROR=806,*/

/*POST ADS RESPONSE CODE
RESPONSE_CODE_ADVERTISE_ADD_ERROR:900,
  RESPONSE_CODE_ADVERTISE_UPDATE_ERROR:901,
  RESPONSE_CODE_ADVERTISE_LIST_ERROR:902,
  RESPONSE_CODE_ADVERTISE_GET_ERROR:903,
  RESPONSE_CODE_ADVERTISE_EXIST:904,
  RESPONSE_CODE_ADVERTISE_NOT_FOUND:905,
RESPONSE_CODE_POST_ADS_ADD_ERROR:1000,
RESPONSE_CODE_POST_ADS_UPDATE_ERROR:1001,
RESPONSE_CODE_POST_ADS_LIST_ERROR:1002,
RESPONSE_CODE_POST_ADS_GET_ERROR:1003,
RESPONSE_CODE_POST_ADS_EXIST:1004,
RESPONSE_CODE_POST_ADS_NOT_FOUND:1005,
RESPONSE_CODE_POST_ADS_RUNNING:1006,
RESPONSE_CODE_POST_ADS_QUERY_ERROR:1007*/
