export const OTP_KEY = 'WQ34Y33CCL53H25F';
export const AES_KEY = 'F5XCSRHBFA52HZZ4';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT = 'LOGOUT';

export const GET_GOOGLE_ERROR = 'GET_GOOGLE_ERROR';
export const GET_GOOGLE_SUCCESS = 'GET_GOOGLE_SUCCESS';
export const GET_GOOGLE_FIRST_ERROR = 'GET_GOOGLE_FIRST_ERROR';
export const GET_GOOGLE_FIRST_SUCCESS = 'GET_GOOGLE_FIRST_SUCCESS';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';

export const FORGOT_PASSWORD_SUCCESS='FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_ERROR='FORGOT_PASSWORD_ERROR';

export const FIND_FRIEND_SUCCESS='FIND_FRIEND_SUCCESS';
export const FIND_FRIEND_ERROR='FIND_FRIEND_ERROR';

export const ADD_FRIEND_SUCCESS='ADD_FRIEND_SUCCESS';
export const ADD_FRIEND_ERROR='ADD_FRIEND_ERROR';

export const LOAD_FRIEND_SUCCESS='LOAD_FRIEND_SUCCESS';
export const LOAD_FRIEND_ERROR='LOAD_FRIEND_ERROR';

export const TRACKING_FRIEND_SUCCESS='TRACKING_FRIEND_SUCCESS';
export const TRACKING_FRIEND_ERROR='TRACKING_FRIEND_ERROR';

export const TRACKING_FRIEND_APP_SUCCESS='TRACKING_FRIEND_APP_SUCCESS';
export const TRACKING_FRIEND_APP_ERROR='TRACKING_FRIEND_APP_ERROR';

export const LOAD_REQUEST_SUCCESS='LOAD_REQUEST_SUCCESS';
export const LOAD_REQUEST_ERROR='LOAD_REQUEST_ERROR';

export const ACCEPT_FRIEND_SUCCESS='ACCEPT_FRIEND_SUCCESS';
export const ACCEPT_FRIEND_ERROR='ACCEPT_FRIEND_ERROR';

export const BLOCK_FRIEND_SUCCESS='BLOCK_FRIEND_SUCCESS';
export const BLOCK_FRIEND_ERROR='BLOCK_FRIEND_ERROR';

export const GET_FRIEND_SUCCESS='GET_FRIEND_SUCCESS';
export const GET_FRIEND_ERROR='GET_FRIEND_ERROR';

export const SEARCH_FRIEND_SUCCESS='SEARCH_FRIEND_SUCCESS';
export const SEARCH_FRIEND_ERROR='SEARCH_FRIEND_ERROR';

export const UNFRIEND_SUCCESS='UNFRIEND_SUCCESS';
export const UNFRIEND_ERROR='UNFRIEND_ERROR';

export const LOAD_BLOCK_SUCCESS='LOAD_BLOCK_SUCCESS';
export const LOAD_BLOCK_ERROR='LOAD_BLOCK_ERROR';

export const UNBLOCK_FRIEND_SUCCESS='UNBLOCK_FRIEND_SUCCESS';
export const UNBLOCK_FRIEND_ERROR='UNBLOCK_FRIEND_ERROR';

export const CHANGE_PASSWORD_SUCCESS='CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_ERROR='CHANGE_PASSWORD_ERROR';

export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_ERROR = 'UPDATE_PROFILE_ERROR';

export const LOAD_INBOX_SUCCESS = 'LOAD_INBOX_SUCCESS';
export const LOAD_INBOX_ERROR = 'LOAD_INBOX_ERROR';

export const GET_LIST_THREAD_SUCCESS = 'GET_LIST_THREAD_SUCCESS';
export const GET_LIST_THREAD_ERROR = 'GET_LIST_THREAD_ERROR';

export const GET_LIST_BY_USERTO_SUCCESS = 'GET_LIST_BY_USERTO_SUCCESS';
export const GET_LIST_BY_USERTO_ERROR = 'GET_LIST_BY_USERTO_ERROR';

export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS';
export const LOAD_USER_ERROR = 'LOAD_USER_ERROR';

export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_ERROR = 'GET_USER_ERROR';

export const SEND_MESSAGE_SUCCESS="SEND_MESSAGE_SUCCESS";
export const SEND_MESSAGE_FAILURE="SEND_MESSAGE_FAILURE";

export const DELETE_MESSAGE_SUCCESS="DELETE_MESSAGE_SUCCESS";
export const DELETE_MESSAGE_ERROR="DELETE_MESSAGE_ERROR";

export const UPIMAGE_SUCCESS = 'UPIMAGE_SUCCESS';
export const UPIMAGE_ERROR = 'UPIMAGE_ERROR';

export const UPLOAD_MUTI_IMAGE_SUCCESS = 'UPLOAD_MUTI_IMAGE_SUCCESS';
export const UPLOAD_MUTI_IMAGE_ERROR = 'UPLOAD_MUTI_IMAGE_ERROR';

export const GET_JOBS_SUCCESS='GET_JOBS_SUCCESS';
export const GET_JOBS_ERROR='GET_JOBS_ERROR';

export const GET_NATION_SUCCESS='GET_NATION_SUCCESS';
export const GET_NATION_ERROR='GET_NATION_ERROR';

export const LOAD_SHOP_SUCCESS = 'LOAD_SHOP_SUCCESS';
export const LOAD_SHOP_ERROR = 'LOAD_SHOP_ERROR';

export const GET_CATEGORY_SUCCESS='GET_CATEGORY_SUCCESS';
export const GET_CATEGORY_ERROR='GET_CATEGORY_ERROR';

export const CREATE_SHOP_SUCCESS='CREATE_SHOP_SUCCESS';
export const CREATE_SHOP_ERROR='GET_CATEGORY_ERROR';

export const UPDATE_SHOP_SUCCESS='UPDATE_SHOP_SUCCESS';
export const UPDATE_SHOP_ERROR='UPDATE_SHOP_ERROR';
export const ADS_SYS_SUCCESS='ADS_SYS_SUCCESS';
export const ADS_SYS_ERROR='ADS_SYS_ERROR';
export const REPORT_SHOP_SUCCESS='REPORT_SHOP_SUCCESS';
export const REPORT_SHOP_ERROR='REPORT_SHOP_ERROR';

export const GET_SHOP_SUCCESS='GET_SHOP_SUCCESS';
export const GET_SHOP_ERROR='GET_SHOP_ERROR';

export const DELETE_SHOP_SUCCESS='DELETE_SHOP_SUCCESS';
export const DELETE_SHOP_ERROR='DELETE_SHOP_ERROR';

export const CREATE_POST_SUCCESS='CREATE_POST_SUCCESS';
export const CREATE_POST_ERROR='CREATE_POST_ERROR';

export const LOAD_POST_SUCCESS='LOAD_POST_SUCCESS';
export const LOAD_POST_ERROR='LOAD_POST_ERROR';

export const GET_POST_SUCCESS='GET_POST_SUCCESS';
export const GET_POST_ERROR='GET_POST_ERROR';

export const UPDATE_POST_SUCCESS='UPDATE_POST_SUCCESS';
export const UPDATE_POST_ERROR='UPDATE_POST_ERROR';

export const DELETE_POST_SUCCESS='DELETE_POST_SUCCESS';
export const DELETE_POST_ERROR='DELETE_POST_ERROR';

export const LIKE_POST_SUCCESS='LIKE_POST_SUCCESS';
export const LIKE_POST_ERROR='LIKE_POST_ERROR';

export const LOAD_COMMENTS_SUCCESS='LOAD_COMMENTS_SUCCESS';
export const LOAD_COMMENTS_ERROR='LOAD_COMMENTS_ERROR';

export const COMMENTS_SUCCESS='COMMENTS_SUCCESS';
export const COMMENTS_ERROR='COMMENTS_ERROR';

export const SEARCH_SUCCESS='SEARCH_SUCCESS';
export const SEARCH_ERROR='SEARCH_ERROR';

export const SEARCH_POST_SUCCESS='SEARCH_POST_SUCCESS';
export const SEARCH_POST_ERROR='SEARCH_POST_ERRORS';
export const SEARCH_NEW_POST_SUCCESS='SEARCH_NEW_POST_SUCCESS';
export const SEARCH_NEW_POST_ERROR='SEARCH_NEW_POST_ERROR';

export const LOAD_NEWSFEED_SUCCESS='LOAD_NEWSFEED_SUCCESS';
export const LOAD_NEWSFEED_ERROR='LOAD_NEWSFEED_ERROR';

export const LOAD_ITEM_SUCCESS='LOAD_ITEM_SUCCESS';
export const LOAD_ITEM_ERROR='LOAD_ITEM_ERROR';

export const BUY_ITEM_SUCCESS='BUY_ITEM_SUCCESS';
export const BUY_ITEM_ERROR='BUY_ITEM_ERROR';

export const UPLOAD_BASE64_SUCCESS='UPLOAD_BASE64_SUCCESS';
export const UPLOAD_BASE64_ERROR='UPLOAD_BASE64_ERROR';
export const UPLOAD_BASE64_2_SUCCESS='UPLOAD_BASE64_2_SUCCESS';
export const UPLOAD_BASE64_2_ERROR='UPLOAD_BASE64_2_ERROR';
/* ADS */
export const ADS_QUERY_SUCCESS='ADS_QUERY_SUCCESS';
export const ADS_QUERY_ERROR='ADS_QUERY_ERROR';

export const GET_PRICE_ADS_SUCCESS='GET_PRICE_ADS_SUCCESS';
export const GET_PRICE_ADS_ERROR='GET_PRICE_ADS_ERROR';

export const GET_ADS_SUCCESS='GET_ADS_SUCCESS';
export const GET_ADS_ERROR='GET_ADS_ERROR';

export const CHANGE_STATE_ADS_SUCCESS='CHANGE_STATE_ADS_SUCCESS';
export const CHANGE_STATE_ADS_ERROR='CHANGE_STATE_ADS_ERROR';

export const UPDATE_ADS_SUCCESS='UPDATE_ADS_SUCCESS';
export const UPDATE_ADS_ERROR='UPDATE_ADS_ERROR';

export const ADD_ADS_SUCCESS='ADD_ADS_SUCCESS';
export const ADD__ADS_ERROR='ADD_ADS_ERROR';

export const LOAD_ADS_SUCCESS='LOAD_ADS_SUCCESS';
export const LOAD_ADS_ERROR='LOAD_ADS_ERROR';

export const LOAD_TRS_SUCCESS='LOAD_TRS_SUCCESS';
export const LOAD_TRS_ERROR='LOAD_TRS_ERROR';

export const GET_MONEY_SUCCESS='GET_MONEY_SUCCESS';
export const GET_MONEY_ERROR='GET_MONEY_ERROR';

export const TRANSFER_REQUEST_SUCCESS='TRANSFER_REQUEST_SUCCESS';
export const TRANSFER_REQUEST_ERROR='TRANSFER_REQUEST_ERROR';

export const TRANSFER_MONEY_SUCCESS='TRANSFER_MONEY_SUCCESS';
export const TRANSFER_MONEY_ERROR='TRANSFER_MONEY_ERROR';

export const LOAD_ADS_VIDEO_SUCCESS='LOAD_ADS_VIDEO_SUCCESS';
export const LOAD_ADS_VIDEO_ERROR='LOAD_ADS_VIDEO_ERROR';

export const GET_ADS_VIDEO_SUCCESS='GET_ADS_VIDEO_SUCCESS';
export const GET_ADS_VIDEO_ERROR='GET_ADS_VIDEO_ERROR';

export const ADS_VIDEO_CREDIT_SUCCESS='ADS_VIDEO_CREDIT_SUCCESS';
export const ADS_VIDEO_CREDIT_ERROR='ADS_VIDEO_CREDIT_ERROR';

export const GET_NOTIFICATION_SUCCESS = 'GET_NOTIFICATION_SUCCESS';
export const GET_NOTIFICATION_ERROR = 'GET_NOTIFICATION_ERROR';
export const LOAD_NOTIFICATION_SUCCESS = 'LOAD_NOTIFICATION_SUCCESS';
export const LOAD_NOTIFICATION_ERROR = 'LOAD_NOTIFICATION_ERROR';
export const UPDATE_NOTIFICATION_SUCCESS = 'UPDATE_NOTIFICATION_SUCCESS';
export const UPDATE_NOTIFICATION_ERROR = 'UPDATE_NOTIFICATION_ERROR';

export const GET_LOGO_SUCCESS='GET_LOGO_SUCCESS';
export const GET_LOGO_ERROR='GET_LOGO_ERROR';
export const UPDATE_LOGO_SUCCESS='UPDATE_LOGO_SUCCESS';
export const UPDATE_LOGO_ERROR='UPDATE_LOGO_ERROR';

export const GET_DES_SUCCESS='GET_DES_SUCCESS';
export const GET_DES_ERROR='GET_DES_ERROR';

export const LOAD_CMT_CHILD_SUCCESS = 'LOAD_CMT_CHILD_SUCCESS';
export const LOAD_CMT_CHILD_ERROR = 'LOAD_CMT_CHILD_ERROR';

export const ACTIVE_REGISTER_SUCCESS = 'ACTIVE_REGISTER_SUCCESS';
export const ACTIVE_REGISTER_ERROR = 'ACTIVE_REGISTER_ERROR';

export const MESSAGE_COUNT_NEW_SUCCESS = 'MESSAGE_COUNT_NEW_SUCCESS';
export const MESSAGE_COUNT_NEW_ERROR = 'MESSAGE_COUNT_NEW_ERROR';
export const LOAD_SHOP_ON_PROFILE_SUCCESS = 'LOAD_SHOP_ON_PROFILE_SUCCESS';
export const LOAD_SHOP_ON_PROFILE_ERROR = 'LOAD_SHOP_ON_PROFILE_ERROR';

export const LOAD_LIST_ACOIN_SUCCESS = 'LOAD_LIST_ACOIN_SUCCESS';
export const LOAD_LIST_ACOIN_ERROR = 'LOAD_LIST_ACOIN_ERROR';
export const SEND_DATA_TO_NL_SUCCESS = 'SEND_DATA_TO_NL_SUCCESS';
export const SEND_DATA_TO_NL_ERROR = 'SEND_DATA_TO_NL_ERROR';
export const UPDATE_NL_SUCCESS = 'UPDATE_NL_SUCCESS';
export const UPDATE_NL_ERROR = 'UPDATE_NL_ERROR';
export const CLICK_ADS_SUCCESS = 'CLICK_ADS_SUCCESS';
export const CLICK_ADS_ERROR = 'CLICK_ADS_ERROR';
export const UNLIKE_SUCCESS = 'UNLIKE_SUCCESS';
export const UNLIKE_ERROR = 'UNLIKE_ERROR';
export const LOAD_LIST_LIKER_SUCCESS = 'LOAD_LIST_LIKER_SUCCESS';
export const LOAD_LIST_LIKER_ERROR = 'LOAD_LIST_LIKER_ERROR';


export const BANNER_WEB_SUCCESS = 'BANNER_WEB_SUCCESS';
export const BANNER_WEB_ERROR = 'BANNER_WEB_ERROR';
