var LanguageVi={
  //DUNG CHUNG
  LOADING:'Đang tải',
  LOAD_MORES: 'Xem thêm',
  HIDDEN_PHONE:'Đã ẩn',
  NOT_NULL:'Không được để trống',
  FAIL_OTP: "Thất bại, hãy thử lại sau vài giây !",
  TEXT_SUCCESS: "Thao tác thành công !",
  TEXT_ERROR: "Thao tác thất bại !",
  SEX_MALE: 'Nam',
  SEX_FEMALE: 'Nữ',
  SEX_OTHER: 'Khác',
  SEX_ALL	:'Tất cả',
  CONFIRM_DELETE: 'Bạn thật sự muốn xóa ?',
  GOOLE_MAPS:'Bản đồ google',
  CHOOSE_OPTION:'Chọn nghề nghiệp',
  OPTION_DEFAULT:'Chọn danh mục',
  OPTION_DEFAULT_PROVINCE:'Chọn nơi cấp',
  SEARCH_ORTHER_TITLE	:'Nhập địa chỉ',
  SEARCH_ORTHER_WARNING	:'Vui lòng nhập địa chỉ !',
  SEARCH_NOTE	:'Nếu bạn muốn thay đổi vị trí khác, hãy kích vào vị trí mong muốn trên bản đồ và nhấn OK.',
    //Trang chu
  NEWS_FEED_TITLE: 'Trang chủ',
  NEWS_FEED_RAOVAT	:'Tin rao vặt',
  //Tim kiem cua hang
  SEARCH_BUTTON_SEARCH: 'Tìm',
  SEARCH_KEYWORD_HINT: 'Từ khóa',
  SEARCH_BUTTON_FORUM: 'Rao vặt',
  SEARCH_BUTTON_AROUND: 'Xung quanh',
  SEARCH_BUTTON_OTHER: 'Nơi khác',
  SEARCH_DISTANCE: 'Khoảng cách: ',
  SEARCH_BUTTON_SEARCHING: 'Đang tìm...',
  SEARCH_SHOP_NO_RESULT: "Chúng tôi không tìm thấy cửa hàng nào. Hãy thử một vị trí khác, hoặc tăng khoảng cách !",
  SEARCH_RESULT_TYPE_LIST	:"Danh sách",
  //Tim kiem tin dang
  FORRUM_SEARCH_TITLE: 'Rao vặt',
  FORRUM_SEARCH_TEXT_BOX_HINT: 'Nhập từ khóa',
  FORRUM_SEARCH_BUTTON_SEARCH: 'Tìm',
  //Màn hình tìm bạn
  FRIEND_REQUEST_TITLE: 'Tìm bạn',
  FRIEND_REQUEST_PHONE_HINT: 'Nhập số điện thoại',
  FRIEND_REQUEST_BUTTON_SEARCH: 'Tìm',
  FRIEND_BUTTON_MAKE_FRIEND: 'Kết bạn',
  FRIEND_BUTTON_ACCEPT: 'Đồng ý',
  FRIEND_BUTTON_CANCEL: 'Hủy',
  FRIEND_BUTTON_BLOCK:'Chặn',
  FRIEND_BUTTON_UNBLOCK: 'Hủy chặn',
  FRIEND_BUTTON_DELETE: 'Xóa',
  FRIEND_RESULT_FOR: 'Kết quả cho: ',
  FRIEND_NO_RESULT: 'Không tìm thấy kết quả nào phù hợp',
  FRIEND_ADDING_WAIT_FOR_COFNIRMATION: "Bạn đã gửi lời mời, chờ xác nhận",
  FRIEND_ADD_SUCCESS: "Gửi lời mời kết bạn thành công",
  FRIEND_PHONE_NOT_FOUND: 'Người dùng không tồn tại, vui lòng kiểm tra lại số điện thoại !',
  //Shop
  SHOP_TITLE: 'Cửa hàng',
  SHOP_BUTTON_CREATE_SHOP	:'Tạo cửa hàng',
  SHOP_BUTTON_CREATE_POST	:'Đăng tin',
  SHOP_COUNT_POST:'Số tin đăng: ',
  SHOP_NUMBER_POST	:' tin đăng',
  SHOP_BUTTON_VIEW	:'Xem',
  SHOP_BUTTON_EDIT	:'Sửa',
  SHOP_BUTTON_DELETE	:'Xóa',
  SHOP_PHONE	:'Điện thoại: ',
  SHOP_ADDRESS	:'Địa chỉ: ',
  SHOP_TIME_WORK	:'Giờ làm việc: ',
  SHOP_LOCATION:'Vị trí cửa hàng',
  SHOP_REPORT_SUCCESS	:'Cảm ơn bạn đã phản hồi về cửa hàng này',
  SHOP_REPORT_ERROR	:'Gửi phản hồi không thành công, vui lòng thử lại sau ít phút',
  SHOP_NOT_TIME_WORK: 'Địa điểm vẫn chưa thiết lập thời gian hoạt động.',
  SHOP_PHOTOS	:'Hình ảnh',
  SHOP_NOT_GET_CURRENT_LOCATION:"Không thể xác định được vị trí của bạn. Mở maps để điều chỉnh !",
  SHOP_NOT_HAVE_POSTS:'Địa điểm chưa có bài đăng !',
  SHOP_NAME	:'Tên cửa hàng: ',
  SHOP_CREATE_VALIDATE_IMAGES_WIDTH_HEIGHT:'Thất bại ! Vui lòng chọn hình ảnh cao ít nhất 300 pixel.',
  SHOP_CREATE_TITLE	:'Tạo Cửa hàng',
  SHOP_UPDATE_TITLE	:'Cập nhật cửa hàng',
  SHOP_CREATE_NAME_HINT	:'Tên',
  SHOP_CREATE_PHONE_HINT	:'Điện thoại',
  SHOP_CREATE_EMAIL_HINT	:'Email',
  SHOP_CREATE_ADDRESS_HINT	:'Địa chỉ',
  SHOP_CREATE_WEBSITE_HINT	:'Website',
  SHOP_CREATE_TIME_T2_TITLE	:'T2_T6',
  SHOP_CREATE_TIME_FROM_HINT	:'Từ',
  SHOP_CREATE_TIME_TO_HINT	:'Tới',
  SHOP_CREATE_TIME_T7_TITLE	:'T7',
  SHOP_CREATE_TIME_CN_TITLE	:'CN',
  SHOP_CREATE_ADDRESS_EXAMPLE: 'Ví dụ: ',
  SHOP_CREATE_HAG_TAG_HINT: "Từ khóa",
  SHOP_CREATE_DESCRIPTION	:'Mô tả',
  SHOP_CREATE_BUTTON_SAVE	:'LƯU LẠI',
  SHOP_CREATE_BUTTON_SAVING:'Đang lưu...',
  SHOP_CREATE_DELETE_IMAGE:'Xóa ảnh',
  SHOP_CREATE_VALIDATE_NAME	:'Vui lòng nhập tên',
  SHOP_CREATE_VALIDATE_PHONE	:'Vui lòng nhập số điện thoại',
  SHOP_CREATE_VALIDATE_EMAIL	:'Vui lòng nhập email',
  SHOP_CREATE_VALIDATE_ADDRESS	:'Vui lòng nhập địa chỉ',
  SHOP_CREATE_VALIDATE_DESCRIPTION	:'Vui lòng nhập mô tả',
  SHOP_CREATE_VALIDATE_AVATAR	:'Vui lòng chọn hình ảnh cho cửa hàng',
  SHOP_NO_SHOPS	:'Không có cửa hàng',
  SHOP_CREATE_VALIDATE_TIME_WORK:'Giờ đóng cửa không được sớm hơn giờ mở cửa',
  SHOP_CREATE_CATETORY_01	:'Danh mục cấp 1',
  SHOP_CREATE_VALIDATE_CATETORY_01	:'Vui lòng chọn danh mục cấp 1',
  SHOP_CREATE_CATETORY_02	:'Danh mục cấp 2',
  SHOP_CREATE_VALIDATE_CATETORY_02	:'Vui lòng chọn danh mục cấp 2',
  SHOP_MSG_DELETE_SHOP_FAILED	:'Xoá cửa hàng thất bại',
  SHOP_MSG_EMPTY_LOCATION	:'Không thể lấy được toạ độ, vui lòng nhập lại địa chỉ hoặc mở!',
  SHOP_MSG_EMPTY_WEBSITE	:'Vui lòng nhập địa chỉ website',
  SHOP_MSG_CREATE_SUCCESS	:'Tạo cửa hàng thành công',
  SHOP_MSG_CREATE_FAILED	:'Tạo cửa hàng thất bại',
  SHOP_MSG_UPDATE_SUCCESS	:'Cập nhật cửa hàng thành công',
  SHOP_MSG_UPDATE_FAILED	:'Cập nhật cửa hàng thất bại',
  POST_MSG_EMPTY_LOCATION_MAPS	:'Không xác định được vị trí, vui lòng mở maps để xác định vị trí và điều chỉnh',
  SHOP_LICENSE	:'Số GPKD',
  //POST
  RESPONSE_CODE_POST_NOT_FOUND  :'Tin đăng không tìm thấy hoặc đã bị xóa',
  POST_TYPE_PRICE	:'Giá',
  POST_TYPE_CALL	:'Gọi',
  POST_TYPE_NEWS_FEED_NOTIFY	:'Tin đăng',
  POST_TYPE_FORUM	:'Tin rao vặt',
  POST_LIKE	:'Thích',
  POST_COMMENT	:'Bình luận',
  POST_ACTION_CANCEL	:'Hủy',
  POST_ACTION_EDIT	:'Sửa',
  POST_ACTION_DELETE	:'Xóa',
  POST_BUTTON_ADS	:'Quảng cáo',
  POST_CREATE_TITLE	:'Tạo tin đăng',
  POST_CREATE_POST_HIDE_PHONE	:'Ẩn số',
  POST_CREATE_POST_ON_TITLE	:'Đăng trên:',
  POST_CREATE_POST_ON_SHOP_TITLE	:'Đăng trên cửa hàng',
  POST_CREATE_POST_ON_FORRUM_TITLE	:'Đăng trên rao vặt',
  POST_CREATE_NAME_HINT	:'Tiêu đề',
  POST_CREATE_PHONE_HINT	:'Điện thoại',
  POST_CREATE_PRICE_HINT	:'Giá',
  POST_CREATE_PRICE_PLACEHOLDER: 'Nhập giá',
  POST_CREATE_CATEGORY01	:'Danh mục cấp 1',
  POST_CREATE_CATEGORY02	:'Danh mục cấp 2',
  POST_CREATE_ADDRESS_HINT	:'Địa chỉ',
  POST_CREATE_SHOP_NOT_EXIST:'Thất bại, cửa hàng không tồn tại !',
  POST_CREATE_SHORT_DESC_TITLE	:'Mô tả ngắn',
  POST_CREATE_DESC_TITLE	:'Mô tả',
  POST_CREATE_HAG_TAG_HINT	:'Từ khóa',
  POST_CREATE_BUTTON_SAVE	:'LƯU',
  POST_CREATE_BUTTON_SAVING	:'Đang lưu...',
  POST_CREATE_VALIDATE_NAME	:'Vui lòng nhập tên',
  POST_CREATE_VALIDATE_POST_ON	:'Vui lòng chọn vị trí đăng',
  POST_CREATE_VALIDATE_PHONE	:'Vui lòng nhập điện thoại',
  POST_CREATE_VALIDATE_PRICE	:'Vui lòng nhập giá',
  POST_CREATE_CHOOSE_CATEGORY	:'Chọn danh mục',
  POST_CREATE_TAG_PLACEHOLDER	:"Mỗi tag được cách nhau bởi dấu ' , '",
  POST_CREATE_VALIDATE_CATEGORY01	:'Vui lòng chọn danh mục cấp 1',
  POST_CREATE_VALIDATE_CATEGORY02	:'Vui lòng chọn danh mục cấp 2',
  POST_CREATE_VALIDATE_ADDRESS	:'Vui lòng nhập địa chỉ',
  POST_CREATE_VALIDATE_SHORT_DESC	:'Vui lòng nhập mô tả ngắn',
  POST_CREATE_VALIDATE_DESC	:'Vui lòng nhập mô tả',
  POST_CREATE_VALIDATE_HASHTAG	:'Vui lòng nhập hashtag',
  POST_CREATE_VALIDATE_IMAGE	:'Vui lòng chọn hình ảnh',
  POST_CREATE_MESSAGh_SUCCESS	:'Tạo tin đăng thành công',
  POST_CREATE_MESSAGE_CREATE_ERROR	:'Tạo tin đăng thất bại',
  POST_CREATE_MESSAGE_UPDATE_ERROR	:'Cập nhật thất bại',
  POST_CREATE_MESSAGE_UPDATE_SUCCESS	:'Cập nhật thành công ',
  POST_VIEW_LIKED	:'Bạn đã like bài viết này',
  POST_VIEW_LOAD_MORE_COMMENTS	:'Tải bình luận cũ hơn',
  POST_VIEW_COMMENT_PLACEHOLDER	:'Nhập bình luận…',
  POST_VIEW_COMMENT_SENDING	:'Đang gửi...',
  POST_VIEW_COMMENT_SEND	:'Gửi',
  POST_COMMENT_REPLY	:'Trả lời',
  POST_COMMENT_REPLY_PLACEHOLDER: 'Viết trả lời ...',
  POST_COMMENT_REPLY_TOTAL_CHILD: ' bình luận',
  //Menu String
  MENU_TITLE	:'Menu',
  MENU_NEWFEED	:'Bản tin',
  MENU_POST:'Đăng tin rao',
  MENU_CHO_RAO_VAT:'Chợ rao vặt',
  MENU_ACCOUNT_INFO:'Thông tin tài khoản',
  MENU_ACCOUNT_INFO_WEB	:'Tài khoản',
  MENU_MESSAGE	:'Tin nhắn',
  MENU_FRIEND	:'Bạn bè',
  MENU_TRANSACTION	:'Giao dịch',
  MENU_NOTIFICATION	:'Thông báo',
  MENU_ADVERTISE	:'Quảng cáo',
  MENU_APP_INFO	:'Thông tin ứng dụng',
  MENU_PROFILE	:'Tài khoản',
  MENU_LOGOUT	:'Đăng xuất',
  SUB_MENU_FRIEND_LIST	:'Bạn bè',
  SUB_MENU_FRIEND_SEARCH	:'Tìm bạn',
  SUB_MENU_COIN_PLUS	:'Nạp coin',
  SUB_MENU_MANUAL_INSTRUCTION	:'Hướng dẫn sử dụng',
  MENU_LOGO	:'Logo thương hiệu',
  MENU_HELP	:'Hỗ trợ',
  //Message String
  MESSAGE_LIST_TITLE	:'Danh sách tin nhắn',
  MESSAGE_TITLE	:'Tin nhắn',
  MESSAGE_INPUT_PLACEHOLDER	:'Nhập tin nhắn...',
  MESSAGE_MSG_DELETE_INBOX	:'Bạn có muốn xoá cuộc hội thoại này không?',
  MESSAGE_MSG_DELETE_INBOX_FAILED	:'Xoá cuộc hội thoại thất bại, vui lòng thử lại!',
  //Friend string
  FRIEND_TITLE	:'Bạn bè',
  FRIEND_MENU_CANCEL_FRIEND	:'Hủy kết bạn',
  FRIEND_MENU_BLOCK	:'Chặn',
  FRIEND_MENU_MOVE_COIN	:'Chuyển Acoin',
  FRIEND_MENU_MESSAGE	:'Nhắn tin',
  FRIEND_MENU_CANCEL	:'Hủy',
  FRIEND_BUTTON_REQUEST	:'Yêu cầu',
  FRIEND_BUTTON_LIST_BLOCK	:'DS Chặn',
  FRIEND_LIST_BLOCK_NULL	:'Danh sách chặn hiện đang rỗng !',
  FRIEND_LIST_REQUEST_NULL	:'Bạn không có lời mời kết bạn nào !',
  FRIEND_LIST_REQUEST_TITLE	:'Trả lời lời mời kết bạn của bạn',
  FRIEND_UNFRIEND_CONFIRM	:'Bạn thật sự muốn hủy kết bạn ?',
  //Move coin string
  MOVE_COIN_TITLE	:'Chuyển Acoin',
  MOVE_COIN_USER_FROM_INFO_TITLE	:'Thông tin người gửi',
  MOVE_COIN_USER_FROM_NAME	:'Người gửi',
  MOVE_COIN_USER_FORM_PHONE	:'Điện thoại',
  MOVE_COIN_USER_FROM_MONEY	:'Acoin',
  MOVE_COIN_USER_TO_INFO_TITLE	:'Thông tin người nhận',
  MOVE_COIN_USER_TO_NAME	:'Người nhận',
  MOVE_COIN_USER_TO_PHONE	:'Điện thoại',
  MOVE_COIN_AMOUNT_HINT	:'Số Acoin chuyển',
  MOVE_COIN_MESSAGE_HINT	:'Nội dung chuyển',
  MOVE_COIN_BUTTON_MOVE	:'CHUYỂN TIỀN',
  MOVE_COIN_WARNING_UNKNOWN_USER_TO	:'Không nhận ra người nhận tiền',
  MOVE_COIN_WARNING_MONEY	:'Vui lòng nhập số tiền cần gửi',
  MOVE_COIN_MONEY_ISNUMBER:'Số Acoin không hợp lệ',
  MOVE_COIN_MONEY: "Số Acoin không đủ",
  MOVE_COIN_WARNING_MESSAGE	:'Vui lòng nhập nội dung gửi tiền',
  MOVE_COIN_OTP_NOTIFICATION	:'Vui lòng kiểm tra mail và lấy otp',
  MOVE_COIN_MOVE_COIN_SUCCESS	:'Chuyển tiền thành công',
  MOVE_COIN_MOVE_COIN_FAILURE	:'Chuyển tiền thất bại',
  MOVE_COIN_WARNING_OTP	:'Thất bại, Mã xác thực không đúng hoặc đã hết hạn !',
  MOVE_COIN_TITLE_1	:'Thông tin giao dịch',
  MOVE_COIN_TITLE_2	:'Xác nhận giao dịch',
  MOVE_COIN_TITLE_3	:'Kết quả giao dịch',
  MOVE_COIN_BUTTON_NEXT	:'Tiếp tục',
  MOVE_COIN_MOVING	:'Đang thực hiện...',
  MOVE_COIN_OTP_NOTIFICATION_WEB	:"Chúng tôi đã gửi một mã xác thực vào email hoặc điện thoại của bạn, hãy điền mã xác thực vào đây để tiếp tục.",
  MOVE_COIN_OTP_NOTIFICATION_WEB2	:'Lưu ý: Mã xác thực chỉ tồn tại 1 phút',
  //Transaction String
  TRANSACTION_TITLE:'Lịch sử giao dịch',
  TRANSACTION_TYPE_PT:'Mua vật phẩm phong thủy: ',
  TRANSACTION_TYPE_BUY_ADS:'Mua quảng cáo: ',
  TRANSACTION_TYPE_RECEIVED_COIN:'Nhận Acoin từ: ',
  TRANSACTION_TYPE_MOVE_COIN	:'Chuyển Acoin cho: ',
  TRANSACTION_TYPE_VIEW_ADS:'Nhận Acoin quảng cáo: ',
  TRANSACTION_TYPE_ADD:'Nạp Acoin',
  TRANSACTION_ID	:'ID',
  TRANSACTION_TIME	:'Thời gian',
  TRANSACTION_GD	:'Giao dịch',
  TRANSACTION_MONEY	:'Số Acoin',
  TRANSACTION_TYPE_BUY_LOGO	:'Mua logo thương hiệu',
  TRANSACTION_TYPE_BUY_VIDEO_ADS	:'Chiến dịch quảng cáo: ',
  TRANSACTION_MONEY_BACK  :'Hệ thống hoàn trả quảng cáo',
  //Advertising list
  ADVERTISE_TITLE	:'Quảng cáo',
  ADVERTISE_BUTTON_VIEW	:'Xem',
  ADVERTISE_VIEWPAGE_BUTTON_ZOOM	:'Phóng to',
  ADVERTISE_VIEWPAGE_BUTTON	:'Bỏ qua',
  ADVERTISE_VIEWPAGE_TITLE_1	:'Bạn đã nhận được ',
  ADVERTISE_VIEWPAGE_TITLE_2	:' Acoin, hãy xem tiếp để nhận được toàn bộ.',
  ADVERTISE_VIEWPAGE_TITLE_3	:'Bạn đã nhận được toàn bộ Acoin của quảng cáo này.',
  ADVERTISE_VIEWPAGE_TITLE_4	:'**Bạn cần xem hết video để được nhận thưởng',
  ADVERTISE_VIEWPAGE_TITLE_5	:'Có thể bạn muốn xem',
  ADVERTISE_TITLE_WEB	:'Xem quảng cáo',
  ADVERTISE_WATCHED :'Đã xem',
  //Post ads string
  POST_ADS_LIST_TITLE	:'Danh sách quảng cáo',
  POST_ADS_LIST_BUTTON_ADD	:'Thêm quảng cáo',
  POST_ADS_LIST_MENU_EDIT	:'Sửa',
  POST_ADS_LIST_MENU_ACTIVE	:'Kích hoạt',
  POST_ADS_LIST_MENU_DELETE	:'Xóa',
  POST_ADS_LIST_MENU_CANCEL	:'Hủy',
  POST_ADS_LIST_MENU_DEACTIVE	:'Dừng',

  POST_ADS_CREATE_TITLE	:'Tạo quảng cáo',
  POST_ADS_CREATE_NAME_HINT	:'Tên chương trình',
  POST_ADS_CREATE_OBJECTIVE_TITLE	:'Hướng đối tượng',
  POST_ADS_CREATE_AGE	:'Tuổi:',
  POST_ADS_CREATE_GENDER	:'Giới tính:',
  POST_ADS_CREATE_JOB	:'Nghề nghiệp:',
  POST_ADS_CREATE_DATE	:'Ngày quảng cáo',
  POST_ADS_RADIUS	:'Bán kính',
  POST_ADS_WARNING_RADIUS	:'Bán kính phải lớn hơn 0',
  POST_ADS_CREATE_ESTIMATE_USER	:'Người tiếp cận: ',
  POST_ADS_CREATE_ESTIMATE_ACOIN	: function(num){
    return 'Chi phí dự kiến ' + num + ' Acoin';
  },
  POST_ADS_CREATE_BUTTON_SAVE	:'LƯU',
  POST_ADS_CREATE_WARNING_NAME	:'Vui lòng nhập tên',
  POST_ADS_CREATE_WARNING_AGE	:'Độ tuổi không hợp lệ',
  POST_ADS_CREATE_WARNING_GENDER	:'Vui lòng chọn giới tính',
  POST_ADS_CREATE_WARNING_JOB	:'Vui lòng chọn nghề ngiệp',
  POST_ADS_CREATE_WARNING_CAN_NOT_RUNNING_ADS	:'Số lượng người tiếp cận không đủ để chạy quảng cáo',
  POST_ADS_UPDATE_TITLE	:'Cập nhật quảng cáo',
  POST_ADS_CREATE_GET_JOB	:'Chọn một ngành nghề',

  POST_ADS_STATE_RUNNING	:'Đang chạy',
  POST_ADS_STATE_PENDING	:'Tạm dừng',
  POST_ADS_VIEW	:'Click: ',
  POST_ADS_CLICK	:'Hiển thị: ',
  POST_ADS_MONEY_COIN	:' Acoin',

  POST_ADS_MSG_DELETE_ADS	:'Bạn muốn xoá quảng cáo này?',
  POST_ADS_MSG_NOT_FOUND	:'Không tìm thấy quảng cáo',
  POST_ADS_MSG_EXIST	:'Quảng cáo đã tồn tại',
  POST_ADS_MSG_ADS_RUNNING	:'Không thể xoá quảng cáo',
  POST_ADS_MSG_UPDATE_FAILED	:'Cập nhật quảng cáo thất bại',
  POST_ADS_MSG_CREATE_FAILED	:'Tạo quảng cáo thất bại',
  POST_ADS_MSG_OUT_MONEY	:'Số tiền không đủ',
  POST_ADS_MSG_QUERY_ERROR	:'Không thể lấy quảng cáo',
  POST_ADS_MSG_LIST_ERROR	:'Không thể lấy danh sách quảng cáo',

  POST_ADS_DELETE_SUCCESS	:'Xóa quảng cáo thành công',
  POST_ADS_DELETE_ERROR	:'Thất bại, quảng cáo đang chạy. Hãy dừng quảng cáo trước',
  POST_ADS_ACTIVE_SUCCESS	:'Kích hoạt quảng cáo thành công',
  POST_ADS_ACTIVE_ERROR	:'Kích hoạt quảng cáo thất bại',
  POST_ADS_PAUSE_SUCCESS	:'Dừng quảng cáo thành công',
  POST_ADS_PAUSE_ERROR	:'Dừng hoạt quảng cáo thất bại',
  POST_ADS_ACTIVE_CONFIRM	:'Bạn muốn kích hoạt quảng cáo này ?',
  POST_ADS_PAUSE_CONFIRM	:'Bạn muốn dừng quảng cáo này ?',
  POST_ADS_COL_ACOIN	:'Chi phí',
  POST_ADS_COL_CLICk	:'SL Click',
  POST_ADS_COL_VIEW	:'SL Hiển thị',
  POST_ADS_COL_ACTION	:'Action',
  POST_ADS_COL_TIME: 'TG bắt đầu',
  POST_ADS_MSG_UPDATE_SUCCESS	:'Cập nhật quảng cáo thành công',
  POST_ADS_MSG_CREATE_SUCCESS	:'Tạo quảng cáo thành công',
  POST_ADS_VALIDATE_DATE_START	:'Ngày bắt đầu là bắt buộc và không được nhỏ hơn ngày hiện tại',
  POST_ADS_VALIDATE_TIME_START	:'Thời gian bắt đầu là bắt buộc và không được nhỏ hơn thời gian hiện tại',
  POST_ADS_VALIDATE_TIME_START_2	:'Thời gian bắt đầu không thể để trống',

  LOGIN_PHONE_HINT	:'Số điện thoại(*)',
  LOGIN_PASSWORD_HINT	:'Mật khẩu(*)',
  LOGIN_LOGIN_BUTTON	:'Đăng Nhập',
  LOGIN_BEGING_LOGGED_IN	:'Đang đăng nhập...',
  LOGIN_FORGET_PASSWORD	:'Quên mật khẩu',
  LOGIN_LOGIN_ERROR	:'Đăng nhập thất bại, vui lòng kiểm tra lại thông tin tài khoản',
  LOGIN_FORGET_PASSWORD_MESSAGE	:'Nhập email hoặc số điện thoại',
  LOGIN_FORGET_PASSWORD_MESSAGE_WARNING	:'Email hoặc Số điện thoại không hợp lệ',
  LOGIN_PHONE_ERROR_ALERT	:'Số điện thoại không hợp lệ',

  /*RESET PASSWORD*/
  RESET_PASSWORD_TITLE	:'Quên Mật Khẩu',
  RESET_PASSWORD_CHECK_EMAIL	:'Yêu cầu thành công, vui lòng kiểm tra email hoặc điện thoại để lấy mật khẩu',
  RESET_PASSWORD_SECURE_CODE	:'Mã bí mật',
  RESET_PASSWORD_NEW_PASSWORD	:'Mật khẩu mới',
  RESET_PASSWORD_RETYPE_NEW_PASSWORD	:'Nhập lại mật khẩu mới',
  RESET_PASSWORD_RESET_BUTTON	:'Đổi mật khẩu',
  RESET_PASSWORD_SECURE_CODE_ERROR	:'Mã bí mật không hợp lệ',
  RESET_PASSWORD_NEW_PASSWORD_ERROR	:'Mật khẩu không hợp lệ',
  RESET_PASSWORD_PASSWORD_NOT_MATCH	:'Mật khẩu không trùng khớp',
  RESET_PASSWORD_RESET_PASSWORD_SUCCESS	:'Đổi mật khẩu thành công, vui lòng login với mật khẩu vừa đổi',
  RESET_PASSWORD_RESET_PASSWORD_FAILURE	:'Đổi mật khẩu thất bại, kiểm tra lại thông tin email, mã bí mật',
  RESET_PASSWORD_TITLE_IN_WEB	:'Đổi mật khẩu',
  RESET_PASSWORD_EMAIL_IN_WEB	:'Nhập địa chỉ email đã đăng ký. Một mã xác nhận sẽ được gửi đến địa chỉ email hoặc số điện thoại của bạn.',
  RESET_PASSWORD_TYPE_EMAIL	:'Email không hợp lệ ',
  RESET_PASSWORD_SENDING	:'Đang thực hiện...',
  RESET_PASSWORD_NEXT	:'Tiếp tục',
  RESET_PASSWORD_CANCEL	:'Hủy',
  RESET_PASSWORD_EMAIL	:'Email',
  RESET_PASSWORD_HAVE_OTP	:'Bạn chưa có mã ?',
  RESET_NOT_FOUND_EMAIL	:'Thất bại, địa chỉ email hoặc số điện thoại không tồn tại',
  LOGIN_FORGET_PASSWORD_SMS	:function (syntax, gateWay) {
    return 'Vui lòng gửi tin nhắn với cú pháp: ' + syntax + ' gửi đến ' + gateWay + ' để lấy lại mật khẩu.'
  },
  /*Register string*/
  REGISTER_TITLE	:'Đăng ký',
  REGISTER_HINT_PHONE	:'Số điện thoại',
  REGISTER_WARNING_PHONE	:'Số điện thoại không hợp lệ',
  REGISTER_HINT_PASSWORD	:'Mật khẩu',
  REGISTER_HINT_GENDER	:'Giới tính',
  REGISTER_HINT_RETYPE_PASSWORD	:'Nhập lại mật khẩu',
  REGISTER_WARNING_PASSWORD	:'Mật khẩu không hợp lệ',
  REGISTER_WARNING_PASSWORD_NOT_MATCH	:'Mật khẩu không trùng khớp',
  REGISTER_HINT_FULLNAME	:'Họ và tên',
  REGISTER_WARNING_FULLNAME	:'Họ và tên quá ngắn, tối thiểu 6 ký tự',
  REGISTER_HINT_EMAIL	:'Email',
  REGISTER_WARNING_EMAIL	:'Email không hợp lệ',
  REGISTER_MESSAGE_PHONE_EXIST	:'Số điện thoại hoặc email đã được đăng ký, vui lòng sử dụng số điện thoại hoặc email khác',
  REGISTER_MESSAGE_ERROR	:'Đăng ký thất bại, vui lòng kiểm tra lại thông tin',
  REGISTER_REFFERENCE_CODE	:'Mã giới thiệu (Tuỳ chọn)',
  REGISTER_REFFERENCE_CODE_ERROR	:'Mã giới thiệu không chính xác, vui lòng kiểm tra lại',
  REGISTER_BUTTON_REGISTER	:'Đăng ký',
  REGISTER_HINT_JOB	:'Nghề nghiệp',
  REGISTER_HINT_DOB	:'Ngày sinh',
  REGISTER_HINT_ADDRESS	:'Địa chỉ',
  REGISTER_TITLE_H1	:'Tìm mọi thứ xung quanh bạn',
  REGISTER_TITLE_H3	:'ĐĂNG KÝ THÀNH VIÊN',
  REGISTER_VALIDATE_BIRTHDAY	:'Độ tuổi lớn hơn 12 và bé hơn 100',
  REGISTER_VALIDATE_PHONE	:'Số điện thoại không hợp lệ',
  CONFIRM_APP_ANDROID	:'Tải Around dành cho Android và duyệt nhanh hơn',
  CONFIRM_APP_IOS	:'Tải Around dành cho Iphone và duyệt nhanh hơn',
  REGISTER_ACTIVE_TITLT	:'Kích hoạt tài khoản',
  REGISTER_ACTIVE_OPT_DESCRIPTION_EMAIL	:'Vui lòng kiểm tra email/sđt để lấy mã xác nhận',
  REGISTER_ACTIVE_OPT_DESCRIPTION_PHONE	:'Vui lòng kiểm tra tin nhắn để lấy mã xác nhận',
  REGISTER_ACTIVE_OPT_BUTTON_SUBMIT	:'Xác nhận',
  REGISTER_ACTIVE_OPT_HINT	:'Nhập mã xác nhận',
  REGISTER_ACTIVE_OPT_ACTIVE_FALSE	:'Kích hoạt thất bại, vui lòng thử lại hoặc liên hệ quản trị để biết thêm chi tiết',
  REGISTER_ACTIVE_OPT_WARNING	:'Mã xác nhận không hợp lệ',
  REGISTER_WARNING_PHONE_OR_EMAIL	:'Vui lòng nhập số điện thoại hoặc email',
  REGISTER_SEND_SMS_MESSAGE	: function (syntax, getwate) {
    return 'Vui lòng gửi tin nhắn với cú pháp: '+ syntax +' gửi đến ' + getwate + ' để lấy mã kích hoạt.'
  },
  REGISTER_HINT_CMND	:'Nhập số chứng minh nhân dân',
  REGISTER_HINT_CMND_DATE	:'Ngày cấp',
  REGISTER_HINT_CMND_PLACE	:'Nơi cấp',
  REGISTER_CHECK_PLOLICY	:'Đồng ý với điểu khoản Around',
  REGISTER_WARNING_CHECK_PLOLICY	:'Vui lòng chấp nhận điều khoản',
  REGISTER_VALIDATE_CMND_DATE :'Ngày cấp không hợp lệ',
  /*Profile string*/
  PROFILE_TITLE	:'Tài khoản',
  PROFILE_HINT_PASSWORD	:'Mật khẩu hiện tại',
  PROFILE_WARNING_PASSWORD	:'Mật khẩu cũ không đúng',
  PROFILE_HINT_NEW_PASSWORD	:'Mật khẩu mới',
  PROFILE_WARNING_NEW_PASSWORD	:'Mật khẩu cũ không đúng',
  PROFILE_HINT_RETYPE_NEW_PASSWORD	:'Nhập lại mật khẩu mới',
  PROFILE_WARNING_PASSWORD_NOT_MATCH	:'Mật khẩu không khớp',
  PROFILE_HINT_FULLNAME	:'Họ và tên',
  PROFILE_WARNING_FULLNAME	:'Họ và tên không hợp lệ',
  PROFILE_HINT_ADDRESS	:'Địa chỉ',
  PROFILE_UPDATE_PASSWORD	:'Mật khẩu không hợp lệ',
  PROFILE_UPDATE_NEW_PASSWORD	:'Trùng mật khẩu hiện tại ',

  PROFILE_WARNING_ADDRESS	:'Địa chỉ không hợp lệ',
  PROFILE_HINT_SEX	:'Giới tính',
  PROFILE_HINT_BIRTHDAY	:'Sinh nhật',
  PROFILE_AVATAR	:'Ảnh đại diện',
  PROFILE_HINT_NATION	:'Quốc gia',
  PROFILE_HINT_PROVINCE	:'Tỉnh thành',
  PROFILE_HINT_DISTRICT	:'Quận/huyện',
  PROFILE_UPDATE_SUCCESS	:'Cập nhật thành công',
  PROFILE_UPDATE_FAILURE	:'Cập nhật thất bại, vui lòng kiểm tra lại thông tin',
  PROFILE_BUTTON_UPDATE	:'Cập nhật',
  PROFILE_TITLE_WEB	:'Thông tin tài khoản',
  PROFILE_UPDATE_TITLE	:'Cập nhật thông tin',
  PROFILE_NAME_WEB	:'Họ và tên',
  PROFILE_PHONE	:'Số điện thoại:',
  PROFILE_ERROR_UPLOAD_IMAGES	:'Chọn hình thất bại !',
  PROFILE_WARNING_NATION	:'Khu vực này chưa có dữ liệu !',
  //My account
  MY_ACCOUNT_TITLE	:'Tài khoản',
  MY_ACCOUNT_BUTTON_EDIT	:'Chỉnh sửa',
  MY_ACCOUNT_BUTTON_ADD_POST	:'Thêm tin đăng',
  MY_ACCOUNT_BUTTON_BUY_ACOIN	:'NẠP THÊM',
  MY_ACCOUNT_TOTAL_POST	:'Tổng số tin rao vặt đã đăng ',
  MY_ACCOUNT_MENU_DELETE_POST	:'Xóa',
  MY_ACCOUNT_MENU_EDIT_POST	:'Chỉnh sửa',
  MY_ACCOUNT_MENU_CANCEL	:'Hủy',
  MY_ACCOUNT_CONFIRM_DELETE	:'Bạn có chắc chắn muốn xóa?',
  MY_ACCOUNT_ACOIN	:'Tài khoản chính: ',
  MY_ACCOUNT_NOT_POST	:'Không có tin đăng',
  MY_ACCOUNT_SHOP_LIST	:'Danh sách cửa hàng',
  //Vat pham phong thuy
  PT_WARNING_OUT_MONEY	:'Số dư tài khoản không đủ',
  PT_BUTTON_BUY	:'Mua',
  PT_BUTTON_BOUGHT	:'Đã mua',
  PT_MSG_BUY_CONFIRM	:'Bạn muốn mua vật phẩm này ?',
  PT_MSG_BUY_FAILED	:'Mua không thành công. Vui lòng thử lại.',
  PT_MSG_BUY_SUCCESS: 'Mua thành công',
  //Thong bao
  NOTIFICATION_NULL	:'Không có thông báo',
  NOTIFICATION_TITLE_WEB	:'Thông báo của bạn',
  NOTIFICATION_COMMENT_POST_WEB	:' bình luận về tin đăng: ',
  NOTIFICATION_LIKE_POST_WEB	:' thích tin đăng: ',
  NOTIFICATION_FRIEND_REQUEST	:' gửi yêu cầu kết bạn',
  NOTIFICATION_FRIEND_ACCEPT	:' đã chấp nhận yêu cầu kết bạn',
  NOTIFICATION_REPLY_POST_WEB	:' đã trả lời bình luận của bạn trên tin đăng: ',
  /*Logo brand*/
  LOGO_BRAND_TITLE	:'Logo thương hiệu',
  LOGO_BRAND_BUTTON_CHOOSE_PHOTO	:'Chọn logo khác',
  LOGO_BRAND_BUTTON_UPDATE	:'Cập nhật',
  LOGO_BRAND_MONEY	:'Chi phí: ',
  LOGO_BRAND_STATE_ACTIVE	:'Đã kích hoạt',
  LOGO_BRAND_STATE_PENDING	:'Chờ duyệt',
  LOGO_BRAND_STATE_CHANGE	:'Chọn mới',
  LOGO_BRAND_STATE_EXPIRED	:'Hết hạn',
  LOGO_BRAND_STATE_DEFAULT	:'Mặc định',
  LOGO_BRAND_MESSAGE_UPDATE_SUCCESS	:'Cập nhật thành công',
  LOGO_BRAND_MESSAGE_UPDATE_FASLE	:'Cập nhật thất bại',
  LOGO_BRAND_MESSAGE_NOT_ENOUGH_MONEY	:'Không đủ tiền để mua logo, vui lòng nạp thêm tiền',
  LOGO_BRAND_MESSAGE_WRONG_SIZE	:'Kích thước hình không hợp lệ, kích thước chuẩn 40x40',
  LOGO_BRAND_STATUS	:'Trạng thái: ',
  LOGO_BRAND_STATE_DATE_EXPIRED	:'Ngày hết hạn: ',
  LOGO_BRAND_BALANCE	:'Số tiền hiện có: ',

  CATEGORY_ALL:'Tất cả danh mục',
  CATEGORY_TITLE:'Danh mục',

  BUY_COIN_TITLE	:'Nạp Acoin',
  BUY_COIN_BUTTON	:'Nạp Acoin',
  BUY_COIN_PRICE: function (num) {
    return num + ' VNĐ'
  },
  BUY_COIN_SUCCESS: function (num) {
    return 'Bạn đã nạp thành công ' + num +' Acoin vào tài khoản'
  },
  BUY_COIN_ERROR: 'Giao dịch không thành công',
  BUY_COIN_CONFIRM: function (input, output) {
    return 'Bạn muốn nạp ' + input+ ' Acoin với chi phí là ' + output+' VNĐ ?'
  },
  BUY_COIN_MODAL_TITLE: 'Phương thức thanh toán',
  BUY_COIN_BUTTON_PAYMENT	:'Thanh toán',
  BUY_COIN_VI_NGAN_LUONG	:'Ví ngân lượng',
  BUY_COIN_ATM_NOI_DIA	:'ATM nội địa',
  BUY_COIN_VISA	:'Visa',
  BUY_COIN_MASTERCARD	:'MasterCard',
  BUY_COIN_BANK_NOTE	: "Lưu ý: Bạn cần đăng ký Internet-Banking hoặc dịch vụ thanh toán trực tuyến tại ngân hàng trước khi thực hiện.",
  BUY_COIN_WARNING_BANKCODE	:'Vui lòng chọn một ngân hàng',
  BUY_COIN_WARNING_PAYMENT_METHOD	:'Vui lòng chọn một phương thức thanh toán',

  LIST_LIKE_TITLE	:'Danh sách thành viên'
}
module.exports = LanguageVi;
